version: '3'
services:
  storage:
    container_name: storage
    build: .
    restart: unless-stopped
    env_file:
      - ./config.env
    ports:
      - '8080:8080'
    environment:
      BASEDIR: "/data/"
    volumes:
      - ./data:/data